### ISSUE TITLE
Show different error messages if not verified and if not sponsored

### ISSUE THREAD

**Issue by adamstallard** [ShenaniganDApp/brightid-discord-bot#3]
I think a good improvement would be to show a different error message if they're not verified yet and if they're not sponsored yet.  If they're not sponsored yet, we should encourage them to go to https://explorer.brightid.org/apps/index.html and get sponsored.  If they're not verified, they should go to https://www.brightid.org/meet and get verified.

**Comment by lucadgtrip** [comment]
I came to the same conclusion. That would be a great addition. 
Most users now ask why it doesn't work.
They never heard of BrightID.

**Comment by 18706325216** [comment]
OK

**Comment by GozieGospel** [comment]
I am having issues claiming the bright token,it pop up that I am not eligible to claim bright token

**Comment by 18706325216** [comment]
一路向前

**Comment by iKaros009** [comment]
Ok

Vào Th 2, 27 thg 9, 2021 lúc 07:29 18706325216 ***@***.***>
đã viết:

**Comment by nikitaostroymov** [comment]
Я пришел к такому же выводу.  Это было бы отличным дополнением.
  Большинство пользователей сейчас спрашивают, почему это не работает.
  Они никогда не слышали о BrightID.

**Comment by likeru088** [comment]
😄

**Comment by zhang553856361** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
